baseURL = "https://miscripts.org/"
languageCode = "en-us"
title = "MiScripts"
theme = "hello-friend-ng"
disableKinds = ["RSS"]

[Author]
  name = "MiScripts"

[params]
  dateform        = "2023-Oct-27"
  dateformShort   = "Oct 27"
  dateformNum     = "2023-10-27"

  disableReadOtherPosts = true
  enableSharingButtons = true

  homeSubtitle = "MiScripts.org is a collaborative initiative developed by a dedicated team of IT professionals from multiple ISDs and schools throughout Michigan."
  
  footerLeft = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
  footerRight = "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

  customCSS = ["css/overrides.css"]

[params.logo]
  logoMark     = ""
  logoText     = "MiScripts"
  logoHomeLink = "/"

[[menu.main]]
  name       = "Home"
  url        = "/"
  weight     = 1

[[menu.main]]
  name       = "About"
  url        = "about"
  weight     = 2

[[menu.main]]
  name       = "Repository"
  url        = "https://wiki.miscripts.org"
  weight     = 3

[[menu.main]]
  name       = "Submissions"
  url        = "submissions"
  weight     = 4

[[menu.main]]
  name       = "Community"
  url        = "community"
  weight     = 4

[[menu.main]]
  name       = "Contact"
  url        = "contact"
  weight     = 5
